[package]
name = "modx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.79"
quote = "1.0.35"
syn = { version = "2.0.58", features = ["full"] }

[dev-dependencies]
dioxus = { version = "0.5.1", features = ["desktop"] }

[lib]
proc-macro = true
